### PR TITLE
Recipes to process up to 2016H dataset

### PR DESCRIPTION
**Pull request by jhgoh**
Preparing a recipe to process up to 2016H dataset.

**Trivial changes**
- Extension 2016H dataset, lumiJSON, pileupWeights, link to google doc
  - Use ReReco JSON file
  - Updated pileup weights (Note: Pileup JSON file does not cover run 284006)

**Changes**
- PAT2CAT_cfg.py takes default globalTag from catDefinitions_cff. (previously: from autoCond)
- Adding crab submit script. We have to use different global tags for promptReco and rereco dataset. Rather than introducing n-more globalTag entries in catDefinitions_cfg, I added "options" column in the google doc. Submit script takes default values from catDefinitions, but override them if any entry is found from the dataset json file.
- catGetDatasetInfo script can use non-official spreadsheet, simply give URL to the google doc (with your own prod version name). Script can read .csv file in local filesystem too.
- getJSONAndPuWeights.py script runs on any host, no need to set up afs. It first tries to open JSON files under afs and fall back to download from official web page.
- move cff/cfi files to sub directories. All producer cfi files are moved to CatProducer/python/producers/
- Electron MVA ID for 80X, together with https://github.com/vallot/cmssw/pull/21

**Work in progress**
- Checking METfilter recipes

https://twiki.cern.ch/twiki/bin/view/CMS/CATToolsTopAnalysis
#624

### CODE REVIEW

**Comment by jshlee** [comment]
+1

**Comment by jshlee** [comment]
nice

**Comment by jhgoh** [comment]
Additional step to run 80X electron MVA (adds MVA weight files under "external" directory)
```
cd $CMSSW_BASE/external
cd slc6_amd64_gcc530/
git clone https://github.com/ikrav/RecoEgamma-ElectronIdentification.git data/RecoEgamma/ElectronIdentification/data
cd data/RecoEgamma/ElectronIdentification/data
git checkout egm_id_80X_v1
```

**Comment by jhgoh** [comment]
runtest OK. Merging this PR.
"work in progress" item is to be done in the next PR (hopefully)

**Pull request merged**
