### PR TITLE
Pseudo top producer

### PR DESCRIPTION
**Pull request by jhgoh**
Pseudo top producer is added.

This module is compatible with MINIAOD's packedGenParticles+prunedGenParticles.
Output are : 
- InputTag("pseudoTop") : pseudo top (and its decay products) in reco::GenParticle format.
- InputTag("pseudoTop", "partons") : simplified partonic top (and also its decay products) in reco::GenParticle format.
- InputTag("pseudoTop", "neutrinos") : all neutrinos used in pseudoTop combination
- InputTag("pseudoTop", "leptons") : all leptons used in pseudoTop cobination in reco::GenJet format
- InputTag("pseudoTop", "jets") : all jets used in pseudoTop combinationin reco::GenJet format. pdgId is set to 5 if B-tagged.

Pseudo top is a "particle level" top quark, reconstructed only with particle level objects in generator record.
- (Dressed) Leptons : anti-kt(0.1) jets with stable lepton in the constituents. Uses leptons and photons from W decay, vetoed hadrons. Takes leading pT lepton to fill lepton flavour. The primary lepton must take at least 50% of total momentum.
- Jets : anti-kt(0.5) jets with reminders of lepton clustering. Added ghost B-hadrons during the clustering to do generator level B tagging. 
- pseudo-W : lepton + neutrino pair with |m(l+vl) - mW| is minimum. In addition to the standard definition, lepton and neutrinos are selected to match flavour (no e-nu_mu pairing). For the lepton-jet channel, dijets are added to pseudo-W.
- pseudo-top : pseudoW + bjet with similar condition in pseudo-W. For the dilepton channel, opposite sign is required.

Particle decay modes are selected using the parton level information.
This is necessary to avoid ambiguity due to acceptance of particle level objects. 
(I think it is not physical to consider fake semileptonic events which are actually from dilepton channel.)

### CODE REVIEW

**Comment by jhgoh** [comment]
More info : event size:

[03:26:43 jhgoh@ui10 test]$ edmEventSize out.root  -v

File out.root Events 49988
Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event) 
recoGenJets_pseudoTop_jets_Ana. 2082.38 471.7
recoGenParticles_pseudoTop_partons_Ana. 796.944 211.476
recoGenParticles_pseudoTop_neutrinos_Ana. 144.861 39.903
recoGenParticles_pseudoTop__Ana. 190.707 38.2794
recoGenJets_pseudoTop_leptons_Ana. 124.587 27.0109
EventAuxiliary 129.671 12.6503
EventSelections 124.65 4.165
edmTriggerResults_TriggerResults__Ana. 76.5387 3.39824
EventProductProvenance 64.3715 3.03551
BranchListIndexes 26.162 2.40234

**Comment by jhgoh** [comment]
More info in physics implications:
- Example particle listing from pseudo top

[ParticleListDrawer] analysing particle collection pseudoTop
 idx  |    ID -       Name |Stat|  Mo1  Mo2  Da1  Da2 |nMo nDa|    pt       eta     phi   |     px         py         pz        m     |
    0 |     6 -          t | 62 |   -1   -1    1    2 |  0  2 | 181.068     -0.488  0.807 |    125.186    130.821    -91.809  171.427 |
    1 |    24 -         W+ | 22 |    0    0    3    4 |  1  2 |  80.494     -0.872  1.607 |     -2.925     80.440    -79.469   58.656 |
    2 |     5 -          b | 23 |    0    0   -1   -1 |  1  0 | 137.661     -0.090  0.375 |    128.111     50.381    -12.340    4.700 |
    3 |   -11 -         e+ | 23 |    1    1   -1   -1 |  1  0 |  30.842     -0.000  2.109 |    -15.797     26.489     -0.013    0.001 |
    4 |    12 -       nu_e | 23 |    1    1   -1   -1 |  1  0 |  51.002     -1.157  1.250 |     16.087     48.399    -73.103    0.000 |
    5 |    -6 -       tbar | 62 |   -1   -1    6    7 |  0  2 | 105.937     -1.395 -2.664 |    -94.081    -48.697   -200.661  172.504 |
    6 |   -24 -         W- | 22 |    5    5    8    9 |  1  2 | 113.419     -0.618 -2.507 |    -91.357    -67.214    -74.588   79.856 |
    7 |    -5 -       bbar | 23 |    5    5   -1   -1 |  1  0 |  18.717     -2.606  1.717 |     -2.724     18.518   -126.074    4.700 |
    8 |     1 -          d | 23 |    6    6   -1   -1 |  1  0 |  79.204     -0.482 -3.024 |    -78.656     -9.301    -39.713    0.013 |
    9 |    -2 -       ubar | 23 |    6    6   -1   -1 |  1  0 |  56.851     -0.578 -1.754 |    -10.363    -55.898    -34.749   -0.006 |
- Parton level vs Particle level - lepton multiplicity
  20141228_cdecaymode
- Pseudo-W and top mass in dilepton channel
  20141228_mpseudotop_dil
- Pseudo-W and top mass in L+J channel
  Note that 2nd W and top are from t->Wb->JJb
  20141228_mpseudotop_lj

**Comment by jshlee** [comment]
Hi John,

Since these objects can be made with cattuples, IMO, I don’t think they should be stored in the ntuple.
We should discuss this in the next meeting.

Cheers,
Jason

On 28 Dec 2014, at 3:13 am, Junghwan John Goh <notifications@github.com<mailto:notifications@github.com>> wrote:

Pseudo top producer is added.

This module is compatible with MINIAOD's packedGenParticles+prunedGenParticles.
Output are :
-   InputTag("pseudoTop") : pseudo top (and its decay products) in reco::GenParticle format.
-   InputTag("pseudoTop", "partons") : simplified partonic top (and also its decay products) in reco::GenParticle format.
-   InputTag("pseudoTop", "neutrinos") : all neutrinos used in pseudoTop combination
-   InputTag("pseudoTop", "leptons") : all leptons used in pseudoTop cobination in reco::GenJet format
-   InputTag("pseudoTop", "jets") : all jets used in pseudoTop combinationin reco::GenJet format. pdgId is set to 5 if B-tagged.

Pseudo top is a "particle level" top quark, reconstructed only with particle level objects in generator record.
-   (Dressed) Leptons : anti-kt(0.1) jets with stable lepton in the constituents. Uses leptons and photons from W decay, vetoed hadrons. Takes leading pT lepton to fill lepton flavour. The primary lepton must take at least 50% of total momentum.
-   Jets : anti-kt(0.5) jets with reminders of lepton clustering. Added ghost B-hadrons during the clustering to do generator level B tagging.
-   pseudo-W : lepton + neutrino pair with |m(l+vl) - mW| is minimum. In addition to the standard definition, lepton and neutrinos are selected to match flavour (no e-nu_mu pairing). For the lepton-jet channel, dijets are added to pseudo-W.
-   pseudo-top : pseudoW + bjet with similar condition in pseudo-W. For the dilepton channel, opposite sign is required.

Particle decay modes are selected using the parton level information.
This is necessary to avoid ambiguity due to acceptance of particle level objects.
(I think it is not physical to consider fake semileptonic events which are actually from dilepton channel.)

---

You can merge this Pull Request by running

  git pull https://github.com/jhgoh/CATTools PseudoTop72x

Or view, comment on, or merge it at:

  https://github.com/vallot/CATTools/pull/40

Commit Summary
-   Imported from KrAFT
-   merged previous PR

File Changes
-   M CatProducer/plugins/BuildFile.xmlhttps://github.com/vallot/CATTools/pull/40/files#diff-0 (2)
-   A CatProducer/plugins/PseudoTopProducer.cchttps://github.com/vallot/CATTools/pull/40/files#diff-1 (807)
-   A CatProducer/python/pseudoTop_cfi.pyhttps://github.com/vallot/CATTools/pull/40/files#diff-2 (14)
-   A CatProducer/test/pseudoTop_cfg.pyhttps://github.com/vallot/CATTools/pull/40/files#diff-3 (66)

Patch Links:
-   https://github.com/vallot/CATTools/pull/40.patch
-   https://github.com/vallot/CATTools/pull/40.diff

**Comment by jhgoh** [comment]
> Since these objects can be made with cattuples, IMO, I don’t think they should be stored in the ntuple. We should discuss this in the next meeting.

-- Only if prunedGenParticles and packedGenParticles are stored.
And yes, it it better to be discussed in the meeting. 
I'm leaving this PR to be merged after then.

**Comment by jhgoh** [comment]
For a fun, I ran the module on ttH sample and plotted M(JJ) of addtional jets.

pseudotop_tth_dl_higgs
pseudotop_tth_sl_higgs

You can see clear peak of H->bbbar; clearly pseudo-top producer is working well.

**Comment by jshlee** [comment]
+1

**Pull request merged**
