### PR TITLE
add a variable in edm by using catGetHFHadronMatching_cff

### PR DESCRIPTION
**Pull request by YoungKwonJo**
https://twiki.cern.ch/twiki/bin/view/CMS/TTbarHbbRun2ReferenceAnalysis#TT_X_splitting
https://twiki.cern.ch/twiki/bin/view/CMSPublic/GenHFHadronMatcher#Event_categorization_example_1

add 
python/GenTtbarCategorizer_cfi.py
plugins/GenTtbarCategorizer.cc

### CODE REVIEW

**Comment by jshlee** [comment]
hi @YoungKwonJo

Shall we merge this?

**Comment by YoungKwonJo** [comment]
Yes, I would like to merge it. 
If we have no problem about merge.

**Comment by jhgoh** [comment]
Questions:
- Doesn't it change the event content of catTuple and event size?
- Isn't it already in CMSSW or planned to be included there?

**Comment by YoungKwonJo** [comment]
1.  we will keep only one-value in catTuple.
   +++++int "GenTtbarCategories" "genTtbarId" "CAT"+++++
2. I have tested it in CMSSW CMSSW_7_4_6_patch6. we don't need to install(download) any-code in the cmssw version.
   However, in old version, we need to add some code. the following is the instruction. 
   https://twiki.cern.ch/twiki/bin/view/CMSPublic/GenHFHadronMatcher#Installation_instructions

**Comment by jshlee** [comment]
we are using CMSSW_7_4_6_patch6 so it should be fine
so this only saves one int per event?

**Comment by YoungKwonJo** [comment]
Yes, it saves one int per event.
the candidates are followings.
+++++++++++++++++
(x can take values 0, 1, 2 depending on the number of b jets from top):
x51: tt+b 
x52: tt+2b 
x53, x54, x55: tt+bb 
x41, x42, x43, x44, x45: tt+cc 
x00: tt+LF
+++++++++
https://twiki.cern.ch/twiki/bin/view/CMSPublic/GenHFHadronMatcher#Event_categorization_example_1

And,  I tested it by using only MINIAODSIM. 
Do you think to test by using AODSIM?

**Comment by jshlee** [comment]
for aodsim, do u want to talk on skype?

**Comment by YoungKwonJo** [comment]
sent a message in your mail.

**Pull request merged**
