### PR TITLE
fix for v7-3-6

### PR DESCRIPTION
**Pull request by jshlee**
fix memory leak in jet producer
added all ele and mu triggers as vector

### CODE REVIEW

**Comment by jhgoh** [comment]
Do you have evt size estimation for catTrigger?

**Comment by jshlee** [comment]
Stringintstdpairs_catTrigger__CAT. 411.79 78.08

**Comment by jshlee** [comment]
I only save the ele and mu triggers that pass

**Comment by jshlee** [comment]
i put this in because the single muon trigger wasnt working

**Pull request merged**
