### PR TITLE
Cat reco example

### PR DESCRIPTION
**Pull request by dhkim81**
This is fully working example of EDAnalyzer to run on catTuple.
Basic kinematic distributions of most of physics objects in the catTuple are produced.

### CODE REVIEW

**Comment by dhkim81** [comment]
histogram_structure

**Comment by dhkim81** [comment]
histogram_structure_2

**Comment by jhgoh** [comment]
Reopened it.

**Comment by jshlee** [comment]
if all variables are saved, wouldnt a tree be better than histos?

**Comment by jhgoh** [comment]
This is aimed to be a fully working example, replacement of existing CATMuonAnalysis.cc
My idea is to give an example for beginners, but also to be used to validate productions as CMS release validation does.

We already have a generic tree producer, so we don't have to put those functions in this simple analyzer.

**Comment by jshlee** [comment]
yep, thats fine then. 
can you get @dhkim81 and @hcwhwang to document these on the kcms wiki once the site is back up.

**Comment by jshlee** [comment]
please add in the instructions in https://www.cms-kr.org/twiki/bin/view/Computing/CATToolsExampleWebHome

**Comment by jhgoh** [comment]
Please move CATMuonAnalysis.cc to plugins directory.
src is not for the plugins. 

Still, I don't know why this dummy analysis module is needed...

**Comment by jhgoh** [comment]
@jshlee Would it be OK to have instruction before merging into main branch?

**Comment by jshlee** [comment]
yep, I would prefer documentation done at the same time

**Comment by jhgoh** [comment]
(related to the issue #61 )

There are several places to put examples:
- (from you reply) https://www.cms-kr.org/twiki/bin/view/Computing/CATToolsExampleWebHome
- (the main page) https://www.cms-kr.org/twiki/bin/view/Computing/CATTools/WebHome#How%20To
- https://github.com/vallot/CATTools/blob/cat72x/CatAnalyzer/README.md

I think 3rd one can be removed.
Link in the 2nd bullet is mostly on dataformat, setup and production. 
Why don't we have analysis examples there?

**Comment by jshlee** [comment]
I put https://www.cms-kr.org/twiki/bin/view/Computing/CATTools/WebHome#Analysis Examples 
to link to https://www.cms-kr.org/twiki/bin/view/Computing/CATToolsExampleWebHome
so that all analysis examples go in one place

**Comment by jshlee** [comment]
@dhkim81 please add in instructions to this new location
https://www.cms-kr.org/twiki/bin/view/Computing/CATTools/AnalysisExamples/WebHome

**Pull request merged**
