### PR TITLE
Add processedLumis

### PR DESCRIPTION
**Pull request by geonmo**

### CODE REVIEW

**Comment by jshlee** [comment]
is this the best way for us to organise processed lumi?

**Comment by jhgoh** [comment]
These processedLumi file is to be used to (re) calculate lumi for each datasets.
They can be placed in the xrootd directory where root files are placed, maybe with the file list in txt format.
Otherwise, we can create new repo to store those prod information and put the link to the repo as a submodule.

**Comment by geonmo** [comment]
Closed this PR.

**Comment by jshlee** [comment]
i prefer to have the processedLumi file in the xrootd directory where root files are placed
i would like a more automated solution to this

**Pull request closed without merging**
