### PR TITLE
new json added

### PR DESCRIPTION
**Pull request by tt8888tt**

### CODE REVIEW

**Comment by jshlee** [comment]
+1

**Comment by jshlee** [comment]
will merge since no one would object to this

**Comment by jhgoh** [comment]
Would you also fix https://github.com/vallot/CATTools/pull/239/files#diff-c78e8dcb38c2c088291a67bfe3bdddf0L51 TriggerResults::CAT -> TriggerResults::RECO?

**Comment by jshlee** [comment]
cool will merge this

**Pull request merged**
