### PR TITLE
remove external scripts

### PR DESCRIPTION
**Pull request by jhgoh**
This PR removes a submodule, external script from cms-kr.
By merging this PR, create-batch needs and other scripts.

### CODE REVIEW

**Comment by jhgoh** [comment]
#699

**Comment by geonmo** [comment]
@jhgoh Why do you remove submodules?

**Comment by jhgoh** [comment]
@geonmo actually, TJ was asking about this, and I realized many people are just copying the create-batch in their workarea (personally, I don't support making copying).

**Comment by jhgoh** [comment]
I'll close this PR, we can reopen this one when requested.

**Pull request closed without merging**
