### PR TITLE
Cleanup analyzer codes

### PR DESCRIPTION
**Pull request by jhgoh**
This PR is to cleanup many analyzer codes.
Physics results must not change at all. Changes are just for code style and better logical structure.

### CODE REVIEW

**Comment by jhgoh** [comment]
On hold until review by @tt8888tt since this PR introduces lots of changes in TtbarDileptonAnalyzer.cc.

**Comment by jshlee** [comment]
+1
I think @tt8888tt will be fine with it
should let @brochero review the single lepton one

**Comment by jhgoh** [comment]
Analysis module for singlelepton (by @brochero ) and dilepton ( @tt8888tt ) are updated to run on the most recent catTuple - significant changes on HLT bit handling. Some example use canses of AnalysisHelper class or simple Handle<int> from CATTriggerBitCombiner are added.

Test was done using private up-to-date catTuple.

**Comment by brochero** [comment]
I have checked the changes. It looks perfect. thanks

**Comment by tt8888tt** [comment]
Totally fine with me.

**Pull request merged**
