### PR TITLE
Update PHYS14 dataset list.

### PR DESCRIPTION
**Pull request by geonmo**
These list can be used to run crab as parameter.

Recent PHYS14 List at 2015/1/20 is used.

### CODE REVIEW

**Comment by jshlee** [comment]
+1

**Comment by jhgoh** [comment]
Do we have expectation on the sample size?

**Comment by jshlee** [comment]
for each sample, i think we need to add in the global tag to be used

**Comment by jhgoh** [comment]
How about defining JSON or xml to bind dataset/reference cfg/cross section info?
(for a mid-term task, but let us not to go too much)

**Comment by jshlee** [comment]
sounds good

**Comment by jhgoh** [comment]
+1
This PR is just a configuration for the production and nothing to do on the code structure.
I think it is safe to merge without detailed review.

**Pull request merged**
