### PR TITLE
GenWeight dataformat

### PR DESCRIPTION
**Pull request by jhgoh**
This PR adds new dataformat for generator level weights - packs up genWeight stuffs into member variables.

Main features:
- Scale weights are split into "scaleUp" and "scaleDown" and the unphysical up+down combinations are dropped, thus users can easily apply scale weights in their analysis codes.
- Parameters for each weight items are stored in the run, GenWeightInfo class to retrieve the information.

```
edmDumpEventContent --run catTuple.root 
Type                   Module        Label     Process   
---------------------------------------------------------
cat::GenWeightInfo     "genWeight"   ""        "CAT"     
```

```
edmDumpEventContent  catTuple.root 
Type                                  Module                   Label             Process   
-------------------------------------------------------------------------------------------
cat::GenWeights                       "genWeight"              ""                "CAT"     
```

Size is somehow large, but I think we have much more gain in convenience.
catGenWeights_genWeight__CAT. 1275.31 905.21

### CODE REVIEW

**Comment by jhgoh** [comment]
Results with 100 events (pay attention on the number of entries/nEvent - that's the size of weight vector for each event)

Calling scaleDownWeights() 
dn

Calling  scaleUpWeights()
up

Calling pdfWeights()
pdfw

**Comment by jhgoh** [comment]
This also affects analysis modules. I'll update analysis modules to run on the new data format.

**Comment by jhgoh** [comment]
All analyzer modules in the main cattools are migrated to use new GenWeights data format.

@brochero , this migration also includes your ttbbLepJets analyzer, this gives better handling of scale up/down variations but I'm keeping the same scale weights ordering for the ntuple level compatibility.

**Comment by brochero** [comment]
I see! Great! Thanks a lot. To me it is a little confused because  scaleUpWeights() can mean Renormalization Up or Factorization Up, depending of the index.

**Comment by jhgoh** [comment]
scaleUpWeights() returns a vector containing 3 variations of muR and muF, (nom/up), (up/nom), (up/up). But anyway, the order in the ttbb lep+jets ntuple is kept as same as the original one.

``` c++
    b_ScaleWeight->push_back(genWeightHandle->scaleUpWeights()[0]);
    b_ScaleWeight->push_back(genWeightHandle->scaleDownWeights()[0]);
    b_ScaleWeight->push_back(genWeightHandle->scaleUpWeights()[1]);
    b_ScaleWeight->push_back(genWeightHandle->scaleUpWeights()[2]);
    b_ScaleWeight->push_back(genWeightHandle->scaleDownWeights()[1]);
    b_ScaleWeight->push_back(genWeightHandle->scaleDownWeights()[2]);
```

**Comment by jhgoh** [comment]
To be more precise,

``` xml
<weightgroup combine="envelope" name="scale_variation">
<weight id="1001"> muR=1 muF=1 hdamp=mt=172.5 </weight>
<weight id="1002"> muR=1 muF=2 hdamp=mt=172.5 </weight>
<weight id="1003"> muR=1 muF=0.5 hdamp=mt=172.5 </weight>
<weight id="1004"> muR=2 muF=1 hdamp=mt=172.5 </weight>
<weight id="1005"> muR=2 muF=2 hdamp=mt=172.5 </weight>
<weight id="1006"> muR=2 muF=0.5 hdamp=mt=172.5 </weight>
<weight id="1007"> muR=0.5 muF=1 hdamp=mt=172.5 </weight>
<weight id="1008"> muR=0.5 muF=2 hdamp=mt=172.5 </weight>
<weight id="1009"> muR=0.5 muF=0.5 hdamp=mt=172.5 </weight>
</weightgroup>
```

For the powheg sample what we are using. This ordering is not guaranteed but let us just assume it to be stable.

This new interface gives
- scaleUpWeights() => [(nom/up), (up/nom), (up/up)]
- scaleDownWeights() => [(nom/dn), (dn/nom), (dn/dn)]

**Comment by brochero** [comment]
Yes, I got it. What I mean is that :
genWeightHandle->scaleUpWeights()[0]-->(up/up)
genWeightHandle->scaleUpWeights()[2]-->(nom/up)

correspond to two different Up variations. Maybe a structure as:
genWeightHandle->scaleFUpWeights()[0]-->(F=up/R=up)
genWeightHandle->scaleFUpWeights()[1]-->(F=up/R=nom)
genWeightHandle->scaleFUpWeights()[2]-->(F=up/R=down)

would be more clear, but it is a personal opinion.

**Comment by jhgoh** [comment]
@brochero actually some text-parsing is necessary to re-group them by muF/muR but this is not trivial since the text format is not uniform for different generators. Rather, I made a function "print()" in GenWeightInfo class thus one can print out the weight indices with information how to access them in the cat::GenWeights.

**Comment by jhgoh** [comment]
Weight distribution from aMC@NLO sample

weights

**Pull request merged**
