### PR TITLE
a bit change of histohelper.py

### PR DESCRIPTION
**Pull request by tt8888tt**
make const k be calculated separately in step 1, once only.

### CODE REVIEW

**Comment by jhgoh** [comment]
Merge?

**Comment by jshlee** [comment]
hey @tt8888tt 
why is kMM and kEE calculated separately?

**Comment by tt8888tt** [comment]
cause I've learned that I have to calculate kMM, kEE at Step1(before MET cut) and use that in all other steps.
or is it wrong?

**Comment by jhgoh** [comment]
Some discussion done yesterday, he was just asking about technical stuffs something like why dont you calculate k factors on the fly.

**Comment by tt8888tt** [comment]
ah then, it's because I just simmply don't know how to, technically.
can't figure out better way...

**Comment by jhgoh** [comment]
Merging this PR. no harm to be merge.

**Pull request merged**
