### PR TITLE
First implementation of cut based electron SF.

### PR DESCRIPTION
**Pull request by jhgoh**
Electron SF's are added for the cut based, medium working point.
Number are preliminary, no uncertainty yet!

### CODE REVIEW

**Comment by jhgoh** [comment]
HOLD until having reliable SF and uncertainties.

**Comment by jhgoh** [comment]
Got an answer from Till, here's hint to understand meaning of each columns.
https://twiki.cern.ch/twiki/bin/viewauth/CMS/HWW2015TriggerResults#Electrons_Tables_or_text_files_f

**Comment by jshlee** [comment]
merge?

**Comment by jhgoh** [comment]
Merging it

**Pull request merged**
