### PR TITLE
Cat examples for partonTop

### PR DESCRIPTION
**Pull request by hcwhwang**
This is an example for the generator level partonTop.

### CODE REVIEW

**Comment by jhgoh** [comment]
So this is the fully working example parton-top in the new catTuple production (cat72x).

The PartonTopProducer (re)produces parton level top quark decay and also gives additional integer flags "channel" and "modes" in case of ttbar production. 
Only top quark "AFTER ISR" are selected, then its decay products W, b and leptons/quarks "BEFORE FSR" are selected. In case of tau decay to leptons, leptons can be accessed with tau->daughter(0). Neutrinos from the tau decay are not included in this collection for the simplicity.

**Comment by jshlee** [comment]
+1

**Comment by hcwhwang** [comment]
bjet1ptpartonvspseudo

**Comment by jhgoh** [comment]
2D version is useful, but I'd like to have previous 1D version as a common educational example.
Or, keep all of them to be a practically useful one.

**Comment by hcwhwang** [comment]
screen shot 2015-02-11 at 11 46 25 am
screen shot 2015-02-11 at 11 47 21 am
screen shot 2015-02-11 at 11 47 48 am

**Comment by jshlee** [comment]
please add in the instructions in https://www.cms-kr.org/twiki/bin/view/Computing/CATToolsExampleWebHome

**Comment by jshlee** [comment]
@hcwhwang what is the status of this pr?

**Comment by jshlee** [comment]
@hcwhwang please add in instructions to this new location
https://www.cms-kr.org/twiki/bin/view/Computing/CATTools/AnalysisExamples/WebHome

**Comment by jshlee** [comment]
@jhgoh and @hcwhwang, shall we merge?

**Pull request merged**
