### PR TITLE
lots of updates to analysis

### PR DESCRIPTION
**Pull request by jshlee**
ttll and h2mu updated for 2016

### CODE REVIEW

**Comment by jhgoh** [comment]
Are the txt files for the Rochester correction? Can it be given in different format with smaller file size?

**Comment by jshlee** [comment]
i assume so... but i would rather use it as is...

**Comment by jshlee** [comment]
the Rochester Correction data files were 20mb which is too large so i removed them

**Comment by jshlee** [comment]
merged since this is analysis only

**Pull request merged**
