### PR TITLE
Add gen weights

### PR DESCRIPTION
**Pull request by jhgoh**
Forgot to add generator weights.
This is necessary for NLO MC especially for aMC@NLO negative weights.

### CODE REVIEW

**Comment by jhgoh** [comment]
HOLD for a second for testing.

**Comment by jhgoh** [comment]
This PR will increase event size, depending on number of weights produced by the generator. 
Size seem to be quite large (just with 100 events, though) Need to understand which is really necessary and which is not.

```
doubles_genWeight_lheWeights_CAT. 2043.67 1852.42
doubles_genWeight_pdfWeights_CAT. 850.96 137.38
double_genWeight_x1_CAT. 29.61 28.82
double_genWeight_x2_CAT. 29.61 28.82
double_genWeight_Q_CAT. 29.47 25.47
doubles_genWeight_genWeights_CAT. 45.31 25.07
int_genWeight_id1_CAT. 25.21 21.09
int_genWeight_id2_CAT. 25.21 21.08
```

**Comment by jhgoh** [comment]
After discussion with Jason, I decided to save only one weight. user can choose index but natural choice must be 0th weight.

**Comment by jhgoh** [comment]
Size reduction done.

```
edmEventSize -v catTuple.root  | grep -i wei
floats_genWeight_pdfWeights_CAT. 443.37 80.64
float_genWeight_x1_CAT. 25.43 24.64
float_genWeight_x2_CAT. 25.43 24.64
float_genWeight_Q_CAT. 25.29 24.5
double_pileupWeight_dn_CAT. 30.03 24.48
double_pileupWeight_up_CAT. 30.03 24.48
double_pileupWeight__CAT. 29.75 24.2
int_pileupWeight_nTrueInteraction_CAT. 27.45 22.89
float_genWeight_genWeight_CAT. 26.41 21.88
float_genWeight_lheWeight_CAT. 26.41 21.88
int_genWeight_id1_CAT. 25.21 21.09
int_genWeight_id2_CAT. 25.21 21.08
```

**Comment by jshlee** [comment]
shall we change the pileupWeight to float too?

**Comment by jhgoh** [comment]
PUWeight also in float.

```
edmEventSize -v catTuple.root  | grep -i wei
floats_genWeight_pdfWeights_CAT. 443.37 80.64
float_genWeight_x1_CAT. 25.43 24.64
float_genWeight_x2_CAT. 25.43 24.64
float_genWeight_Q_CAT. 25.29 24.5
float_pileupWeight_up_CAT. 25.85 23.35
float_pileupWeight_dn_CAT. 25.85 23.35
float_pileupWeight__CAT. 25.57 23.07
int_pileupWeight_nTrueInteraction_CAT. 27.45 22.89
float_genWeight_genWeight_CAT. 26.41 21.88
float_genWeight_lheWeight_CAT. 26.41 21.88
int_genWeight_id1_CAT. 25.21 21.09
int_genWeight_id2_CAT. 25.21 21.08
```

**Comment by jshlee** [comment]
hahah slightly lower

**Comment by jhgoh** [comment]
size estimate w/ 100 events, but no reason to keep double.

**Comment by jhgoh** [comment]
Size estimate w/ 1000 events, visible effect.

```
[18:38:34 jhgoh@ui10 prod]$ edmEventSize -v catTuple0.root  | grep -i weight
doubles_pdfWeight__CAT. 831.327 105.39
double_pdfWeight_x2_CAT. 11.061 9.682
double_pdfWeight_x1_CAT. 11.061 9.669
double_pdfWeight_Q_CAT. 11.047 6.13
double_pileupWeight_dn_CAT. 11.103 3.524
double_pileupWeight_up_CAT. 11.103 3.524
double_pileupWeight__CAT. 11.075 3.496
int_pdfWeight_id1_CAT. 7.021 2.344
int_pdfWeight_id2_CAT. 7.021 2.338
int_pileupWeight_nTrueInteraction_CAT. 7.245 2.307
[18:38:46 jhgoh@ui10 prod]$ edmEventSize -v catTuple1.root | grep -i weight
floats_genWeight_pdfWeights_CAT. 424.485 55.084
float_genWeight_x1_CAT. 7.043 5.743
float_genWeight_x2_CAT. 7.043 5.742
float_genWeight_Q_CAT. 7.029 5.48
float_pileupWeight_dn_CAT. 7.085 3.275
float_pileupWeight_up_CAT. 7.085 3.275
float_pileupWeight__CAT. 7.057 3.247
int_genWeight_id1_CAT. 7.021 2.344
int_genWeight_id2_CAT. 7.021 2.338
int_pileupWeight_nTrueInteraction_CAT. 7.245 2.307
float_genWeight_genWeight_CAT. 7.141 2.207
float_genWeight_lheWeight_CAT. 7.141 2.207
```

**Comment by jhgoh** [comment]
I'll press merge button today if there's no objection.

**Comment by jshlee** [comment]
+1

**Comment by geonmo** [comment]
+1

**Pull request merged**
