### PR TITLE
update for Backport from 7_6_X: ttbar event categorizer, miniAOD jet flavour improvements

### PR DESCRIPTION
**Pull request by YoungKwonJo**
update it for "Backport from 7_6_X: ttbar event categorizer, miniAOD jet flavour improvements"
https://github.com/vallot/CATTools/issues/226

added three lines in line 304 as like in the link.
https://github.com/YoungKwonJo/cmssw/blob/NewGenHFHadronMatcher_cmssw747p2/PhysicsTools/JetMCAlgos/plugins/JetFlavourClustering.cc#L304

However, we need to remove it(CatProducer/plugins/GenTtbarCategorizer.cc) after merged https://github.com/cms-sw/cmssw/pull/11559.

I have tested the code by using a command in CATTools/CatProducer/prod.

> cmsRun PAT2CAT_cfg.py runOnRelVal=True useMiniAOD=True runGenTop=True

### CODE REVIEW

**Comment by jhgoh** [comment]
Thank you for update. Just for a confirmation - is the code in cmssw same to yours?

**Comment by YoungKwonJo** [comment]
I used the recipe in the link.
https://www.cms-kr.org/twiki/bin/view/Computing/CATTools/DataSets/WebHome#2015 September v7-4-2
So I used CMSSW_7_4_12_patch4.
However I used the CaTTools as pull request version.

And, if we have to go cmss76x, we need to update few-things.
https://github.com/YoungKwonJo/CATTools/blob/cat75x/CatProducer/python/catGenHFHadronMatching_cff.py#L57 
 remove comment(#) in L57
 remove CatProducer/plugins/GenTtbarCategorizer.cc
 add comment(#) in L59

**Comment by jhgoh** [comment]
Event categorizer가 74X에 백포팅 될 예정이예요. 현재 PR이 올라가 있는데, 이게 나중에 merge되고 나면 plugin이 중복되기 때문에 미리 cattools에서 제거하고, 대신 현재 올라간 PR을 git-cms-merge-topic 하도록 installation recipe을 업데이트 하면 됩니다.

여기서 확인하고 싶은 것은 현재 74X backporting 으로 올라간 categorizer와 영권이형이 catTools에 포함시킨 categrizer가 같은 코드인지 확인했으면 합니다.

**Comment by YoungKwonJo** [comment]
categorizer가 같지는 않습니다. w to b, w to c를 count할수 있도록 업데이트가 더 되어 있습니다.
아래와같은 설명이 추가가 되었습니다.
-     Then, b jets from W are identified, i.e. jets containing a b hadron from W->b decay
-     They are encoded in the ID as numberOfBjetsFromW*1000, i.e.
-     0xxx: no b jets from W in acceptance
-     1xxx: 1 b jet from W in acceptance
-     2xxx: 2 b jets from W in acceptance
-   
-     Then, c jets from W are identified, i.e. jets containing a c hadron from W->c decay, but no b hadrons
-     They are encoded in the ID as numberOfCjetsFromW*10000, i.e.
-     0xxxx: no c jets from W in acceptance
-     1xxxx: 1 c jet from W in acceptance
-     2xxxx: 2 c jets from W in acceptance

앞으로 recipe.
remove > git cms-merge-topic YoungKwonJo:NewGenHFHadronMatcher_cmssw747p2
add  > git cms-merge-topic bartosik-desy:CMSSSW_7_4_X_GenTtbarCategorizer

**Comment by jshlee** [comment]
could you update this on the twiki please

**Comment by jhgoh** [comment]
Updated instruction.

``` bash
git-cms-merge-topic 11559
# git cms-merge-topic YoungKwonJo:NewGenHFHadronMatcher_cmssw747p2
```

**Comment by jshlee** [comment]
shall we merge this now?

**Comment by jhgoh** [comment]
+1

**Comment by jhgoh** [comment]
Will merge after unit test.

**Comment by jhgoh** [comment]
Some messages during testing. @YoungKwonJo  can we simply ignore it?

```
In extremely rare instances the mismatch could be caused by a difference in the machine precision in which case make sure the original jet collection is produced and reclustering is performed in the same job.
%MSG
%MSG-w NullTransverseMomentum:  JetFlavourClustering:genJetFlavourInfos  01-Oct-2015 19:47:47 CEST Run: 1 Event: 1579
dropping input candidate with pt=0
%MSG
%MSG-e JetPtMismatch:  JetFlavourClustering:genJetFlavourInfos  01-Oct-2015 19:47:48 CEST Run: 1 Event: 1589
The reclustered and original jet 0 have different Pt's (72.0359 vs 72.6514 GeV, respectively).
Please check that the jet algorithm and jet size match those used for the original jet collection and also make sure the original jets are uncorrected. In addition, make sure you are not using CaloJets which are presently not supported.
```

**Comment by jhgoh** [comment]
Some errors during unit test with AODSIM. I'll redo the test  from fresh setup.
```
----- Begin Fatal Exception 01-Oct-2015 20:34:29 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /afs/cern.ch/work/j/jhgoh/TopAnalysis/CATTools/CMSSW_7_4_12_patch4/src/CATTools/CatProducer/test/../prod/PAT2CAT_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.AttributeError'>
'EDProducer' object has no attribute 'JetPartonMapSource'
----- End Fatal Exception -------------------------------------------------
Failure to run PAT2CAT from AODSIM: status 90
status = 23040
```

**Comment by jhgoh** [comment]
Deleted comment about JetPartonMap stuff because it is not related w/ this PR.

**Comment by jhgoh** [comment]
This PR does nothing to the message from JetFlavourClustering, it is 100% due to the main CMSSW codes.
I think this PR can be merged, ready to go.

**Comment by jhgoh** [comment]
Merging this PR as the recipe already updated.

**Pull request merged**
