### PR TITLE
Separate KinReco module

### PR DESCRIPTION
**Pull request by jhgoh**
#163

Separate candidate combination and kinematic reco module.

Ported version of KinReco seem to have some problem to reproduce top mass, this have to be fixed.

### CODE REVIEW

**Comment by jhgoh** [comment]
For a tracking - mTop1, mTop2, mW1 and mW2 plots from various KinReco algorithms.
I suspect some bug in TopKinRecoUtils.cc... need investigation.

cmt1
cmt2
cmw1
cmw2

**Comment by jhgoh** [comment]
Bug found. fix will be provided soon.

**Comment by jhgoh** [comment]
m1
m2

**Comment by jhgoh** [comment]
m1
m2
m3
m4

**Comment by jshlee** [comment]
what changed??

**Comment by jhgoh** [comment]
There were typos in the routine to extract coefficients, thus top, W mass from the fit was wrong. The last commit fixes the problem thus gives correct top and W masses.

**Comment by jhgoh** [comment]
Fixed conflicts
Use random number generator service
Fixed python syntax error

**Pull request merged**
