### PR TITLE
catGetDatasetInfo lists prod directories too

### PR DESCRIPTION
**Pull request by jshlee**
have catGetDatasetInfo check if database is correct while creating sample list files

### CODE REVIEW

**Comment by jshlee** [comment]
updated to pick the latest version of the production

**Comment by jhgoh** [comment]
Hmm.. Are you going to remove dataset list prod_*.txt file?

**Comment by jshlee** [comment]
not straight away, but i think it's nicer to have all info in one place.

**Comment by jhgoh** [comment]
Original idea of catListDatasets script was to list up xrood from the prod__.txt file, before filling up the spreadsheet. Theose prod__.txt files are directly used in the production, right?

**Comment by jshlee** [comment]
for v745 we did production by reading the spread sheet and not the text files.

**Comment by jhgoh** [comment]
OK. it's now clear. BTW, how about having another tab for Name:DataSetName:title:colour, etc? I think these information are unchanged in different campaigns.

**Pull request merged**
