### PR TITLE
2015 Preliminary Pileup weight

### PR DESCRIPTION
**Pull request by jhgoh**
New but preliminary recipe is available here
https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/2451/1/2/1/1/2/1.html

80mb +- 5% uncertainty for pileupCalc.py input parameters, MC pu distribution from CMSSW startup 25ns cfg.

There was a bug while running accumulate function, initial value "0" had to be "0.0".

### CODE REVIEW

**Comment by jhgoh** [comment]
#189

**Comment by jshlee** [comment]
since we dont really need to save the 3 variables because they are all derived from 1 variable.
how about we make this similar to the JER?
something that can be called quickly from FWlite.

**Comment by jhgoh** [comment]
Basically no, otherwise we have to 
- store addPileupInfo as whole 
- or re-implement PU reweighting algorithms from the scratch. 

I think saving 3 numbers is not harmful.

**Comment by jshlee** [comment]
ah because of the other bx..
no worries then

**Comment by jshlee** [comment]
merge?

**Comment by jhgoh** [comment]
Can anybody check weight distribution using the official sample? I tried to run it using the relval sample but this just gives only one weight & nTrueInteraction.

**Comment by jshlee** [comment]
we need some testers!

**Comment by jshlee** [comment]
screen shot 2015-10-13 at 8 59 40 pm
screen shot 2015-10-13 at 8 59 32 pm
screen shot 2015-10-13 at 8 59 22 pm

there is a lot of events with weight of 0. is this normal?

**Comment by jhgoh** [comment]
Bugfix to be added soon.

**Comment by jhgoh** [comment]
Output from the pileupCalc.py, "true" mode, mininum bias cross section = 80mb +- 5%.
Peak position is at ~10.

screen shot 2015-10-14 at 12 08 44 pm

Printing out the nTrueInteractions from the PileupInfo, it gives 35 and does not change in event.

**Comment by jhgoh** [comment]
Comparison between true and observed mode
screen shot 2015-10-14 at 12 16 05 pm

**Comment by jshlee** [comment]
merge?

**Comment by jhgoh** [comment]
Still in doubt to use this out of box, but let us merge now and look at the distr. with full stat.

**Pull request merged**
