### PR TITLE
Metjec

### PR DESCRIPTION
**Pull request by jalmond**

### CODE REVIEW

**Comment by jshlee** [comment]
is this for RD only or both?
can u add in labels?

**Comment by jalmond** [comment]
This is for RD and MC. I will try and add labels now.

**Comment by jshlee** [comment]
does this mean MC will need to be redone?
how important is this?

**Comment by jalmond** [comment]
I think the effect will be small. It is just updating the JEC used in the MET. For that it is not urgent.  I also saved the xy shifted met for our trilepton analysis. It would be nice to have this in the MC also but It can wait i guess. It depends on whether we expect to have a new MC production anytime soon.

**Comment by jhgoh** [comment]
I think we need new campaign, say v806 to introduce the dataformat change.

We already have some catTuples with v805 setup. Using samples with and without new variables can introduce crash when used.

**Comment by jshlee** [comment]
yep im good with v806

**Comment by jhgoh** [comment]
Merging this PR

**Pull request merged**
