### PR TITLE
change analyzer code (branch names)

### PR DESCRIPTION
**Pull request by tt8888tt**
combined muon SF up & down and electron SF up & down to lepton SF up & down.

### CODE REVIEW

**Comment by jhgoh** [comment]
Can we simply assume 100% positive correlation bet'n mu scales and electron scales?

**Comment by tt8888tt** [comment]
You mean like... up SF for electron is saved as 'lepton_weght' in branch 'mueff_u' too...?

**Comment by jhgoh** [comment]
Previous code saves weights from mu and electrons separately.

**Comment by jshlee** [comment]
for ee and mumu channel, it shouldnt matter, but for emu channel, this wouldn't work.
i dont think there will be 100% positive correlation, so e and mu should be done separately.

**Comment by jhgoh** [comment]
Codes are up to date to reflect those comments.

**Pull request merged**
