### PR TITLE
added puppi jets and met to cattuple

### PR DESCRIPTION
**Pull request by jshlee**
added puppi jet and met
added medium muon id
updated jec to Summer15_50nsV2_MC
added pfMVAMet

### CODE REVIEW

**Comment by jshlee** [comment]
i'll merge this and start the new production now!

**Comment by jshlee** [comment]
merging this since latest production was done with this commit

**Comment by monttj** [comment]
The logic should be the other way around. It should be merged before the official production?

**Comment by jshlee** [comment]
yes, i was waiting for someone else to merge it...
i'll do that from now on.

**Pull request merged**
