### PR TITLE
Modify CATSecVertex from Lepton+Lepton to pfCandidate+pfCandidates.

### PR DESCRIPTION
**Pull request by geonmo**
### Introduction

On issue #311, A new method which make a secvtx candidates from pfCandidates is better efficiency than conventional method. So, I will replace old to new method for official catSecVtx producer.
### Feature
- Replace CATSecVtx to pfCandidate method.
- Add legacy plugins for CatAnalyzer's catJpsiDraw directory.
- Add some scripts to draw and compare producer's performance.

### CODE REVIEW

**Comment by jshlee** [comment]
are CatAnalyzer/test/catJpsiDraw/plugins/CATSecVertexXXProducer.cc required?

**Comment by geonmo** [comment]
@jshlee No, it did not required. It is just for code review.

**Comment by jhgoh** [comment]
Why vertex fit is there for V3? I thought just copying secondary vertex collection is enough... was it assuming pion legs??

**Comment by jshlee** [comment]
i think u can delete all the different versions and have it all in one plugin with different options

**Comment by geonmo** [comment]
@jhgoh Actually, no reason for that. It is just due to cloning from original code.
@jshlee Yes, you are right. I will put them all to one plugin next week.

**Comment by jshlee** [comment]
what is the status of D*?

**Pull request merged**
