### PR TITLE
Switch boolean flags to bitset to reduce file size

### PR DESCRIPTION
**Pull request by jhgoh**
Boolean flags can be packed into a std::bitset 
This allows file size reduction little bit, without information loss.

The reduction factor seem to be not that dramatic - overall 1.3% using inclusive ttbar sample.
GenTop object reduces by 3%(819Bytes/evt ->791Bytes/evt)  because this object has lots of boolean flags. (still not that significant)

Variable names will not be stored in the data structure, therefore if an analyzer open the catTuple without dataformat library can have trouble to decode the meaning of each bits.
But in the usual use-cases, I expect analyzers uses the full framework or at least FWLite to open the catTuples, therefore access to each flags are done with member function. 

catTuple from original v803
<pre>
$ edmEventSize -v catTuple.root  | grep CAT                            
catGenTops_catGenTops__CAT. 2818.83 818.742
catJets_catJets__CAT. 4037.31 759.17
catGenWeights_genWeight__CAT. 1062.62 718.735
catJets_catJetsPuppi__CAT. 1919.45 333.538
recoGenJets_pseudoTop_jets_CAT. 1469.35 287.696
catSecVertexs_catDstars_D0Cand_CAT. 783.121 258.9
patTriggerObjectStandAlones_catTrigger__CAT. 1809.56 252.99
catMuons_catMuons__CAT. 503.843 223.352
catElectrons_catElectrons__CAT. 1024.57 205.677
catPhotons_catPhotons__CAT. 636.574 150.08
catMETs_catMETsPuppi__CAT. 291.004 135.442
catMETs_catMETs__CAT. 290.154 132.784
catFatJets_catFatJets__CAT. 354.68 91.946
catSecVertexs_catDstars_DstarCand_CAT. 247.792 69.458
recoVertexs_catVertex__CAT. 150.782 60.186
recoGenParticles_pseudoTop_neutrinos_CAT. 183.6 44.476
catSecVertexs_catDstars_JpsiCand_CAT. 187.274 37.593
recoGenJets_pseudoTop_leptons_CAT. 142.011 37.376
recoGenParticles_pseudoTop__CAT. 162.312 34.543
catTriggerBits_catTrigger__CAT. 442.917 18.094
intss_genJetHadronFlavour_ancestors_CAT. 104.305 14.749
intss_genJetHadronFlavour_hadronAncestors_CAT. 69.133 10.419
ints_genJetHadronFlavour_nCHadron_CAT. 55.011 8.504
ints_genJetHadronFlavour_nBHadron_CAT. 55.011 7.812
edmTriggerResults_TriggerResults__CAT. 78.789 5.291
int_pileupWeight_nTrueInteraction_CAT. 7.245 3.271
float_pileupWeight_up_CAT. 7.085 3.223
float_pileupWeight_dn_CAT. 7.085 3.219
float_pileupWeight__CAT. 7.057 3.195
int_GenTtbarCategories_genTtbarId_CAT. 7.245 3.131
int_GenTtbarCategories30_genTtbarId_CAT. 7.273 3.131
int_GenTtbarCategories40_genTtbarId_CAT. 7.273 3.111
int_catVertex_nGoodPV_CAT. 7.077 3.087
int_catVertex_nPV_CAT. 7.021 3.051
bool_BadChargedCandidateFilter__CAT. 4.221 2.383
bool_BadPFMuonFilter__CAT. 4.081 2.243
</pre>

catTuple with bitset
<pre>
catGenTops_catGenTops__CAT. 2550.28 791.235
catJets_catJets__CAT. 3984.68 754.941
catGenWeights_genWeight__CAT. 1056.62 718.611
catJets_catJetsPuppi__CAT. 1886.91 329.727
recoGenJets_pseudoTop_jets_CAT. 1469.35 287.696
catSecVertexs_catDstars_D0Cand_CAT. 763.789 256.98
patTriggerObjectStandAlones_catTrigger__CAT. 1809.56 252.99
catMuons_catMuons__CAT. 473.697 215.334
catElectrons_catElectrons__CAT. 1028.06 199.14
catPhotons_catPhotons__CAT. 614.824 140.512
catMETs_catMETsPuppi__CAT. 291.004 135.442
catMETs_catMETs__CAT. 290.154 132.784
catFatJets_catFatJets__CAT. 349.85 90.412
catSecVertexs_catDstars_DstarCand_CAT. 245.824 69.394
recoVertexs_catVertex__CAT. 150.782 60.186
recoGenParticles_pseudoTop_neutrinos_CAT. 183.6 44.476
catSecVertexs_catDstars_JpsiCand_CAT. 187.19 37.609
recoGenJets_pseudoTop_leptons_CAT. 142.011 37.376
recoGenParticles_pseudoTop__CAT. 162.312 34.543
catTriggerBits_catTrigger__CAT. 442.917 18.094
intss_genJetHadronFlavour_ancestors_CAT. 104.305 14.749
intss_genJetHadronFlavour_hadronAncestors_CAT. 69.133 10.419
ints_genJetHadronFlavour_nCHadron_CAT. 55.011 8.504
ints_genJetHadronFlavour_nBHadron_CAT. 55.011 7.812
edmTriggerResults_TriggerResults__CAT. 78.789 5.291
int_pileupWeight_nTrueInteraction_CAT. 7.245 3.271
float_pileupWeight_up_CAT. 7.085 3.223
float_pileupWeight_dn_CAT. 7.085 3.219
float_pileupWeight__CAT. 7.057 3.195
int_GenTtbarCategories_genTtbarId_CAT. 7.245 3.131
int_GenTtbarCategories30_genTtbarId_CAT. 7.273 3.131
int_GenTtbarCategories40_genTtbarId_CAT. 7.273 3.111
int_catVertex_nGoodPV_CAT. 7.077 3.087
int_catVertex_nPV_CAT. 7.021 3.051
bool_BadChargedCandidateFilter__CAT. 4.221 2.383
bool_BadPFMuonFilter__CAT. 4.081 2.243
</pre>

### CODE REVIEW

**Comment by jhgoh** [comment]
#606

**Comment by jhgoh** [comment]
<pre>
Branch					Redux factor	Difference
catGenTops_catGenTops__CAT.		 3.35967% 	-27.507 bytes/evt
catPhotons_catPhotons__CAT.		 6.37527% 	-9.568 bytes/evt
catMuons_catMuons__CAT.			 3.58985% 	-8.018 bytes/evt
catElectrons_catElectrons__CAT.		 3.17828% 	-6.537 bytes/evt
catJets_catJets__CAT.			 0.557056% 	-4.229 bytes/evt
catJets_catJetsPuppi__CAT.		 1.1426% 	-3.811 bytes/evt
catSecVertexs_catDstars_D0Cand_CAT.	 0.741599% 	-1.92 bytes/evt
catFatJets_catFatJets__CAT.		 1.66837% 	-1.534 bytes/evt
catGenWeights_genWeight__CAT.		 0.0172525% 	-0.124 bytes/evt
catSecVertexs_catDstars_DstarCand_CAT.	 0.092142% 	-0.064 bytes/evt
catSecVertexs_catDstars_JpsiCand_CAT.	-0.0425611% 	+0.016 bytes/evt
</pre>

**Comment by jshlee** [comment]
+1 super like!

**Comment by jshlee** [comment]
rebase

**Comment by jhgoh** [comment]
rebased

**Comment by jhgoh** [comment]
This will introduce too much complicated changes, so I'm not considering to add this to the master branch. I'm closing this PR, we can come back to similar issues if we have new idea.

**Pull request closed without merging**
