### PR TITLE
electron pid

### PR DESCRIPTION
**Pull request by jshlee**
added Lepton.h
having common variables between electrons and muons
while keeping all the same functionalities

for both electrons and muons
    bool isTight() const { return isTight_; }
    bool isMedium() const { return isMedium_; }
    bool isLoose() const { return isLoose_; }

for muons
    bool isGlobalMuon() const { return isGlobalMuon_; }
    bool isSoftMuon() const { return isSoftMuon_; }
    bool isPFMuon() const { return this->isPF(); }
    bool isTightMuon() const { return this->isTight(); }
    bool isMediumMuon() const { return this->isMedium(); }
    bool isLooseMuon() const { return this->isLoose(); }

for electrons
    bool isVeto() const {return electronID("veto");}
    bool isMediumMVA() const {return electronID("wp90");}
    bool isTightMVA() const {return electronID("wp80");}

### CODE REVIEW

**Comment by jshlee** [comment]
@monttj @jhgoh 
not the nicest way, but easiest to maintain.
we can start the discussion here on how best to implement this.

**Comment by jhgoh** [comment]
This is nice enough :-)

**Comment by jshlee** [comment]
how about trig MVA and nonTrig MVA? do we need both?

**Comment by jshlee** [comment]
how about a common lepton class to uniformise a lot of the common variables between muons and electrons like ID, isolations, etc

**Comment by jhgoh** [comment]
will you update classdef xml, etc too?

**Comment by jhgoh** [comment]
Fails to pass unit test

```
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 09-Oct-2015 15:08:44.667 CEST
----- Begin Fatal Exception 09-Oct-2015 15:08:44 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'outpath'
   [2] Calling event method for module PoolOutputModule/'out'
   [3] Calling produce method for unscheduled module CATElectronProducer/'catElectrons'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::ValueMap<bool>
Looking for module label: egmGsfElectronIDs
Looking for productInstanceName: heepElectronID-HEEPV60

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
09-Oct-2015 15:08:44 CEST  Closed file root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_7_4_6_patch6/RelValZMM_13/MINIAODSIM/74X_mcRun2_asymptotic_realisticBS_v0_2015Jul24PU-v1/00000/487C927D-6732-E511-9FB3-0025905B85AA.root
```

**Comment by jshlee** [comment]
should work now

**Comment by jhgoh** [comment]
Unit test OK.

**Pull request merged**
