### PR TITLE
Cat trigger dataformat

### PR DESCRIPTION
**Pull request by jhgoh**
Yet another trial to reduce event size from trigger information.

**Changes**
  - Introduces new dataformat cat::TriggerBits and cat::TriggerNames
    - cat::TriggerNames stores trigger names and reco filter names to luminosityblock
    - cat::TriggerBits saves (prescale)x(triggerBit) in vector<unsigned short>, keeping the same order of cat::TriggerNames
  - CATTriggerBitsCombiner uses cat::Trigger* dataformats

**Expected file size reduction**
  * Before: 102.27+82.85+28.39+27.23+27.19+23.67+22.27 = 313.87
  * After: 53.7 (ignored data in luminosityBlock)
```
patTriggerObjectStandAlones_catTrigger__CAT. 2460.14 505.89
patPackedTriggerPrescales_patTrigger__PAT. 2079.8 102.27
edmTriggerResults_TriggerResults__HLT. 1092.25 82.85
edmTriggerResults_TriggerResults__PAT. 139.17 28.39
edmTriggerResults_TriggerResults__RECO. 109.31 27.53
edmTriggerResults_TriggerResults__SIM. 101.17 27.23
edmTriggerResults_TriggerResults__CAT. 99.17 27.19
bool_BadChargedCandidateFilter__CAT. 24.21 23.67
bool_BadPFMuonFilter__CAT. 22.81 22.27

catTriggerBits_catTrigger__CAT. 476.82 53.7
```

### CODE REVIEW

**Comment by jhgoh** [comment]
#606

**Comment by jshlee** [comment]
+1
cool!

**Comment by jhgoh** [comment]
Validated by comparing other frameworks in tcH phys.

**Comment by jhgoh** [comment]
Merging  this PR. The original TriggerResults are kept at this moment, but maybe we can drop them in the next round of PR.

**Pull request merged**
