### PR TITLE
Add DeepFlavor charm tagging

### PR DESCRIPTION
**Pull request by gbyu**
It includes DeelFlavor Charm tagging variables

### CODE REVIEW

**Comment by jshlee** [comment]
+1
when do you need this prod to be done?

**Comment by gbyu** [comment]
Whenever new production is made. The sooner the better actually so that we can test the variable for 13 TeV ongoing charged Higgs analysis

**Comment by gbyu** [comment]
For 8_0_21 or higher (less than v81x), charm tagging is not included by default. According to the DeepFlavor wiki, it needs additional setup as below. 
----------------------------------------------

For DeepCMVA and DeepCSV do:
cmsrel 8_0_21

#get the code
git cms-merge-topic -u mverzett:DeepFlavourCMVA-from-CMSSW_8_0_21
#get the training
mkdir RecoBTag /DeepFlavour/data/
cd RecoBTag /DeepFlavour/data/
wget http://home.fnal.gov/~verzetti//DeepFlavour/training/DeepFlavourNoSL.json
wget http://mon.iihe.ac.be/~smoortga/DeepFlavour/CMSSW_implementation_DeepCMVA/Model_DeepCMVA.json
cd -
#compile (for a very long time and many times...)
scram b

**Comment by jhgoh** [comment]
#685

**Comment by jhgoh** [comment]
The instruction for the next production should be added to include this recipe.
https://github.com/vallot/CATTools/wiki/Campaigns-80X

**Comment by gbyu** [comment]
Is this change included in the CATTools? I can't find the change in current cat80x. When is the next production?

**Comment by jshlee** [comment]
we can do next prod when it is needed by users.

**Comment by jhgoh** [comment]
merging this PR.

**Pull request merged**
