### PR TITLE
New KinFitter for TTLJ and FCNH

### PR DESCRIPTION
**Pull request by jhgoh**
New kinematic fitter to the lepton+jet channel is developed.

This fitter first computes exact neutrino pz solutions by solving quadratic equation and finds minimum "chi2", (M(lep+nu)-80.4)^2 + (M(lep+nu+jet1)-172.5)^2 + (M(jet2+jet3)-80.4)^2 + (M(jet2+jet3+jet4)-172.5)^2. 

This PR only adds the fitter into the CATTools, not applied to any analyzer plugins for now.
The code is first developed on a flat ntuple, it should be easy to back port to your own ntuples.

### CODE REVIEW

**Comment by geonmo** [comment]
@jhgoh who is responsible for TTLJ analysis? I think that the users need to review this PR.

**Comment by jhgoh** [comment]
@geonmo actually, this KinFit is be tested/used by HYU group, for TTLJ and FCNC.

**Comment by geonmo** [comment]
+1

**Comment by jhgoh** [comment]
Merging this PR. The fitter can be used in the analysis macro as well.

**Pull request merged**
