### PR TITLE
GenTop bugfix

### PR DESCRIPTION
**Pull request by jhgoh**
Searching begin to begin is meaningless.

### CODE REVIEW

**Comment by jhgoh** [comment]
Fix for #79

**Comment by jshlee** [comment]
is this to be merged??

**Comment by jhgoh** [comment]
I don't know, I made this PR to push @monttj to clarify this is expected or not but I don't remember what is his answer.

**Comment by jhgoh** [comment]
Hmm.. I was raising this issue expecting some answer from responsible to this code by making them 2b annoying with this PR.
I don't know. Personally, I'll never use this.
I think this is NOT TO BE MERGED for now. Same argument to #96 . I'm closing this.

**Pull request closed without merging**
