### PR TITLE
switch to stream EDProducer, unique_ptr

### PR DESCRIPTION
**Pull request by jhgoh**
switch to stream::EDProducer
use std::unique_ptr

### CODE REVIEW

**Comment by jshlee** [comment]
shall we add this for the new prod?

**Comment by jhgoh** [comment]
After doing runtime test.

**Comment by jshlee** [comment]
are u going to test?

**Comment by jhgoh** [comment]
Did you update cattools install. recipe - electron id git-cms-merge-topic?

**Pull request merged**
