### PR TITLE
PseudoTopProducer in TQAF

### PR DESCRIPTION
**Pull request by jhgoh**
PseudoTopProducer is integrated into the TQAF. Remove it from CATTools to avoid module name conflict.

### CODE REVIEW

**Comment by jhgoh** [comment]
#98

**Comment by jshlee** [comment]
shall i merge this?

**Comment by jhgoh** [comment]
Not an urgent issue if nobody is using 74X/75X release.

**Comment by jhgoh** [comment]
There was agreement to merge this PR at the CATTools meeting.

**Pull request merged**
